version: "3.3"

services:

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://sabahatomar:newpassword@db/task_manager
      - FLASK_APP=run:create_app

    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sabahatomar
      - POSTGRES_PASSWORD=newpassword
      - POSTGRES_DB=task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    privileged: true  # <--- this line gives privileged access


volumes:
  postgres_data:
